"use strict";

/*
- OBJECT-ORIENTED PROGRAMMING IS A PROGRAMMING PARADIGM BASED ON THE CONCEPT OF OBJECTS.

- WE USE OBJECTS TO MODEL(DESCRIBE) REAL-WORLD OR ABSTRACT FEATURES.

- OBJECTS MAY CONTAIN DATA(PROPERTIES) AND CODE (METHODS). BY USING OBJECTS, WE PACK DATA AND THE CORRESPONDING BEHAVIOR INTO ONE BLOCK.

- IN OOP, OBJECTS ARE SELF-CONTAINED PIECES/BLOCKS OF CODE.

- OBJECTS ARE BUILDING BLOCKS OF APPLICATIONS, AND INTERACT WITH ONE ANOTHER.

- INTERACTIONS HAPPEN THROUGH A PUBLIC INTERFACE (API): METHODS THAT THE CODE OUTSIDE OF THE OBJECT CAN ACCESS AND USE TO COMMUNICATE WITH THE OBJECT.

*/

// WHY OOP ACTUALLY EXISTS?
// THIS PARADIGM WAS DEVELOPED WITH THE GOAL OF ORGANIZING CODE (TO MAKE IT MORE FLEXIBLE AND EASIER TO MAINTAIN)
// BEFORE OPP, WE MIGHT HAVE A BUNCH OF CODES GATHERED ACROSS MULTIPLE FUNCTIONS OR EVEN IN THE GLOBAL SCOPE, WITHOUT ANY STRUCTURE, AND THIS PARTICULAR STYLE OF CODE IS USUALLY CALLED SPAGHETTI CODE \, AND SPAGHETTI CODE MAKES IT VERY HARD TO MAINTAIN LARGE CODE BASES AND ADD NEW FUNCTIONALITIES TO IT.
// SO THE IDEA OF OOP WAS BASICALLY CREATED AS A SOLUTION TO THIS PROBLEM
