"use strict";

/*
- OBJECT-ORIENTED PROGRAMMING IS A PROGRAMMING PARADIGM BASED ON THE CONCEPT OF OBJECTS.

- WE USE OBJECTS TO MODEL(DESCRIBE) REAL-WORLD OR ABSTRACT FEATURES.

- OBJECTS MAY CONTAIN DATA(PROPERTIES) AND CODE (METHODS). BY USING OBJECTS, WE PACK DATA AND THE CORRESPONDING BEHAVIOR INTO ONE BLOCK.

- IN OOP, OBJECTS ARE SELF-CONTAINED PIECES/BLOCKS OF CODE.

- OBJECTS ARE BUILDING BLOCKS OF APPLICATIONS, AND INTERACT WITH ONE ANOTHER.

- INTERACTIONS HAPPEN THROUGH A PUBLIC INTERFACE (API): METHODS THAT THE CODE OUTSIDE OF THE OBJECT CAN ACCESS AND USE TO COMMUNICATE WITH THE OBJECT.

*/
